### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Casabuena-AngelRose** [PUP-BSIT/ex7-sixth_sense#1]
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/Armedilla_Alliyah_Samantha.html#L15

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/Armedilla_Alliyah_Samantha.html#L26

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/designstyle.css#L87-L87
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/designstyle.css#L1-L1

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/Escuro_JohnDeniel.html#L49

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

We do not put elements inside headings. Unordered list tag should outside the headings.
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/Escuro_JohnDeniel.html#L17-L26
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/Escuro_JohnDeniel.html#L29-L38

Instead of using url link, you can use local image.
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/Escuro_JohnDeniel.html#L53-L69

Max of 1 extra new line for readability purpose: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/Armedilla_Alliyah_Samantha.html#L44-L45
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/style.css#L34-L35
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/style.css#L39-L40

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/Escuro_JohnDeniel.html

Unnecessary Files: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/work1.html
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/work2.html
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/work3.html
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/work4.html
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/work5.html
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Armedilla_Alliyah_Samantha/Armedilla.html

Remove Unnecessary Space: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Escuro_John_Deniel/style.css#L1-L2

**Comment by armedillaalliyah** [comment]
Thank you!

**Comment by Escuro-JohnDenielL** [comment]
Thank you!
