### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Danay-MaryJoy** [PUP-BSIT/ex7-sixth_sense#2]
Hi, good day!😊 @Trinidad-KianLee , @RosarioAngelica 
 
Please note that all class names should be written in **kebab case** and IDs should be written in **snake case**
see this link> https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR15hTWkgykAvEQujS74FHgJUa9UxiKSLF6C5MzuxYQZct0Vu7jQYWUyQAI_aem_AfbRDN52Fnw7TRXXR4uiXndLIWpv01TwxZMo7TvdPUV2YlzDnVgyePFxmQR_sexUJd0GnHMcLQM2qJdkeo00i445#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Trinidad_KianLee/Trinidad_KianLee.html#L23

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Rosario_Angelica/Rosario_Angelica.html#L26

Additionally, it is advisable to **delete all unnecessary files** in your folders. This include empty files. 
 https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

Moreover, please use snake case in naming your **file names**. For example 'my_surname.html'.
 https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

**CSS Styling review:**

Always use **single space** after parenthesis, see the attached link > https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR15hTWkgykAvEQujS74FHgJUa9UxiKSLF6C5MzuxYQZct0Vu7jQYWUyQAI_aem_AfbRDN52Fnw7TRXXR4uiXndLIWpv01TwxZMo7TvdPUV2YlzDnVgyePFxmQR_sexUJd0GnHMcLQM2qJdkeo00i445#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Trinidad_KianLee/trinidad-style.css#L58C1-L59C8

**Comment by RosarioAngelica** [comment]
Thank you!
