### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Dupo-JudyAnn** [PUP-BSIT/ex7-sixth_sense#3]
Remove unnecessary files in the repo

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Gasta_Marc_Oliver/Gasta_Marc_Oliver.html#L24

Class names should be all lower case and separated by hyphen
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Gasta_Marc_Oliver/Gasta_Marc_Oliver.html#L28

Exceeded 80 columns
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Gasta_Marc_Oliver/gasta-style.css#L1
Add a single space after the selector/s and before "{".
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Gasta_Marc_Oliver/gasta-style.css#L33
Exceeded 80 columns
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/Ilagan_Andrei_Jireh/ILAGAN_ANDREI%20JIREH.html#L10
Use CSS for styling. 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g286f540102c_1_0

**Comment by Gasta-Marc-Oliver** [comment]
Thank You!

**Comment by Gasta-Marc-Oliver** [comment]
Thank you!

**Comment by IlaganJireh** [comment]
Thank you!!
