### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Danay-MaryJoy** [PUP-BSIT/ex7-sixth_sense#4]
Code review for index files:

Hi, everyone😊

We've noticed you put the elements inside the heading tags. We should not put elements, i.e unordered lists/lists inside the headings tags. List tags must place outside the heading tags. 
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L15C9-L25C14

Please do not exceed 80 columns per line, see the attached link: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR15hTWkgykAvEQujS74FHgJUa9UxiKSLF6C5MzuxYQZct0Vu7jQYWUyQAI_aem_AfbRDN52Fnw7TRXXR4uiXndLIWpv01TwxZMo7TvdPUV2YlzDnVgyePFxmQR_sexUJd0GnHMcLQM2qJdkeo00i445#slide=id.g24da8de92d7_0_0

https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L18
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L19
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L20
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L21
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L22
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L23
CSS exceeds 80 lines
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.css#L26

You might want to add extra new line here, a single space, this is for readability.
https://github.com/PUP-BSIT/ex7-sixth_sense/blob/b3aa4bfeb566a4d7e53e3ea049b8f28f346c207e/index.html#L12C5-L13C28

**Comment by RosarioAngelica** [comment]
Thank you!

**Comment by Trinidad-KianLee** [comment]
Thank you!
